service: reacttrpc-starter
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  stage: ${env:NODE_ENV}

  logRetentionInDays: 180
  versionFunctions: false

  environment:
    JWT_SECRET: ${env:JWT_SECRET}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}
    GOOGLE_REDIRECT_URI: ${env:GOOGLE_REDIRECT_URI}

    DATABASE_URL: ${env:DATABASE_URL}
    APP_VERSION: ${env:APP_VERSION}

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true

functions:
  http-api:
    handler: src/functions/server.handler
    events:
      - httpApi:
          path: '/trpc/{any+}'
          method: '*'

  version:
    handler: src/functions/version.handler
    events:
      - httpApi:
          path: /version
          method: GET
