name: Pull request

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, labeled, unlabeled]

permissions:
  pull-requests: read 
  contents: read   

jobs:
  check_labels:
    timeout-minutes: 1
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Check if points label added
        uses: actions/github-script@v7
        with:
          script: |
            const labels = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }).then(response => response.data.labels.map(label => label.name));

            if (labels.includes("dependabot[bot]")) return;

            const pointsLabels = labels.filter(label => label.startsWith("points:"));

            if(pointsLabels.length === 0)
              core.setFailed('Points label is not added')

      - name: Check if PR type label added
        uses: actions/github-script@v7
        with:
          script: |
            const labels = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }).then(response => response.data.labels.map(label => label.name));

            const typeLabels = ["bug", "enhancement", "dependencies"];
            const issueTypeLabel = labels.filter(label => typeLabels.includes(label));

            if(issueTypeLabel.length === 0)
              core.setFailed('Type label is not added')

  check_title:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: ".+"
          allowed_prefixes: "feat:,fix:,chore:,build(deps):,build(deps-dev)"
          prefix_case_sensitive: false
          min_length: 10
          max_length: -1
